### PR TITLE
Simple dockerized dev environment setup

### PR DESCRIPTION
**Pull request by ktopolski**
I had to set it up to work on #122 , maybe someone else could use it as well :)

### CODE REVIEW

**Comment by larquin** [comment]
I have a few concerns about introducing a containerized environment in the standard project, and I'm not totally convinced it reduces the barrier to entry for contributing to standard. If anything, my thoughts are that it adds complexity to the project unnecessarily, as it requires us to maintain our code and the container itself. 

Containerized Environments assume a specific workflow, and can obfuscate troubleshooting issues. I'd advise us to avoid endorsing a specific workflow when we're working on standard. For developers unfamiliar with working in container based dev environments, merely wrestling with the state of the container, e.g. "is it up or down?", can cause unnecessary frustration. 

The image we're using in this PR also runs as root, which is something I wouldn't advise as a good standard of practice in any containerized environment. Ideally our container would set up a user, or change the user at container run time using an entry point script. 

If standard was an application, and we were building it for a specific containerized deployment, I'd be more open to containerizing our dev process, but if we're looking to add a container to alleviate development concerns in a library, I'm not certain we're addressing the pain points of working with different versions of say, rubocop.

**Comment by ktopolski** [comment]
Hello Micah,

Thank you for your feedback! I always enjoy a constructive one.

I have no hard feelings for this one in particular. It's not like I'm trying to push a specific standard workflow here, it's more like there isn't any - neither in `README` nor in `CONTRIBUTING`. I wouldn't mind changing this PR to just include a "Contributing" section with few instructions on how to setup local env for standard development.

As for the Dockerfile itself, I was sacrificing good partice of non-root user set via entrypoint for easier readability. I do, of course, agree that it is best practice - I was just worried about the same thing you are in this comment - barrier of entry.

Given all of that, I guess we can either drop the docker based env for dedicated contributing section in readme or support both local and docker. Then, we could bring back best practices as the docker flow wouldn't be the only one mentioned in contributing, tchus people not familiar with it wouldn't hit the wall.

**Comment by larquin** [comment]
Gotcha, I think we're aligned. 

Maybe we can drop the docker based environment and shore up our contributing section so people have a better handle on how to get started with standard. I definitely think we're lacking in that regard so it can be confusing on how to start hacking on the project.

**Comment by ktopolski** [comment]
Closing this in favor of #124 , thanks for your input @larquin :)

**Pull request closed without merging**
