### PR TITLE
Add readme section for running in editors, starting with vim

### PR DESCRIPTION
**Pull request by will**
ref #32

@searls let me know if this is what you were thinking, I can word it however.

### CODE REVIEW

**Comment by searls** [comment]
LGTM - thanks!

**Comment by searls** [comment]
Fixes #32

**Comment by searls** [comment]
Hey Will, do you find that this actually works? It's not enough for me. Setting this and `:echo g:ale_ruby_rubocop_executable` returns `standardrb`, but each file is still getting errors from what seem to be rubocop's default settings

**Comment by will** [comment]
Yeah, I do think it's working for me:

With the line in my vimrc, I get
image

Commenting it out I get
image

**Comment by searls** [comment]
Huh, indeed this works fine on my second computer and not my first. Lost 45 minutes trying to answer why.

Welp.

(╯°□°）╯︵ ┻━┻

**Pull request merged**
